version: '3.3'

services:

  nginx:
    restart: always
    image: nginx:1.21.0-alpine
    working_dir: /var/www/html
    volumes:
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs/nginx:/var/log/nginx
      - ./:/var/www/html
    ports:
      - "51080:80"
      - "51443:443"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    networks:
      - backend
    depends_on:
      - php
    links:
      - php

  php:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: php-fpm -F --allow-to-run-as-root
    volumes:
      - ./:/var/www/html
    env_file:
      - ./.env
    networks:
      - backend

networks:
  backend:
    driver: bridge